version: '3.4'
services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.25.0
    ports: 
      - "3000:8080"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw,authkey
      #- COMMUNITY_EXTENSIONS=gwc-azure-blobstore
      #- STABLE_EXTENSIONS=wps,csw,authkey,web-resource,vectortiles,css,mbstyle,feature-pregeneralized,flatgeobuf,importer,pyramid       
      #- COMMUNITY_EXTENSIONS=gwc-azure-blobstore,gwc-distributed,cog,dataidr-catalog-loader,jdbcconfig,jdbcstore,pgraster       
      - COMMUNITY_PLUGIN_URL=https://build.geoserver.org/geoserver/2.25.x/community-latest       
      - STABLE_PLUGIN_URL=https://build.geoserver.org/geoserver/2.25.x/ext-latest       
      - GEOSERVER_VERSION=2.25-SNAPSHOT       
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx5G     
    volumes:
      #- ./opengeoserver-data-config:/opt/geoserver_data/:Z
      - ./geoserver_gwc_blobstore:/opt/default/blobstore/:Z       
      - ./geoserver_data:/opt/geoserver_data/:Z       
      - ./additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup     
    healthcheck:       
      test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1       
      interval: 1m       
      retries: 3       
      timeout: 20s